### ISSUE TITLE
Random integer mistakes

### ISSUE THREAD

**Issue by Commandersand** [Skyrat-SS13/Skyrat13#1259]
## Reproduction:
Sometimes chemicals will just fluctuate by 0.000001 when they react
Biogen biomass also does it randomly but it removes the decimal properly once it updates

**Comment by CinderWC** [comment]
I have looked into the matter with Azarak and others. And Azarak themselves has said that this is an intended feature of Fermichem. Which is a chemistry rework that was done on Citadel (Our Upstream) about a year ago or so.
The 0.0001 values are part of the fluctuations when reactions happen and are intended.

However, whether these fluctuations are actually a good change or not, is another issue.
But since it is indeed an intended mechanic, this is not an issue that will be pursued further.

Yell at Fermi to stop bullying poor Chem mains upstream if this is something that you would like to pursue further
