### ISSUE TITLE
lavaland syndie outpost has broken consoles and no lavaland proof suits

### ISSUE THREAD

**Issue by Commandersand** [Skyrat-SS13/Skyrat13#1434]
## Round ID:
1178

## Date and Time of Issue:
4/20

## What Map did this Issue occur on:
box i think yeah

## Reproduction:
>go to syndie comms outpost
>click on atmos consoles
>white window that doesn't go away
>screwdriver/rescrewdriver doesn't work

this is only a problem because they have to generate power after a while and you can't
have gas flow without breaking into the room

also there's mining equipment but no mining suit or any way to get past the lava, it just doesn't make sense? there's space suits but they're only useful for if there's a breach

**Comment by AshInTheWind** [comment]
They also have a golem mining reward's vendor and no way to go out and mine, unless you count making a land bridge with an RCD. Maybe give them the parts to make a Firefighter, along with the basic tools? A cargo clamp, mech drill, and an ore box. That way they actually fully experiment with their departments (xenobio/viro/botany/circuits) without compromising security.

Not that it'll stop miners from metagaming the hell out of the place and yelling "Syndicate outpost!" the instant they see it and then they proceed to break in and steal everything they can lay their grubby mitts on.

**Comment by CinderWC** [comment]
@Commandersand May i know what BYOND Version you are on? This is relevant to the issue

**Comment by BobJogaIsForkinBanned** [comment]
No one fucked with the screen down here. You should make an issue on citadel, since it's been a recurring problem - yes our syndie base is modified, but even before it was we had this bug.

**Comment by ForrestWick** [comment]
The mining vendor and ORM board are literally only there just in case you manage to get some mining done.

**Comment by Strazyplus** [comment]
lavaland syndie outpost has lot of bugs and problems, I am sorry i didnt take screenshots but I will go off memory and state the bugs. currently I do not know how to host and spawn my own lavaland syndie outpost. to do this

BUGS I HAVE FOUND ON [lavaland syndie outpost]

AI CAMERAS
The station AI can see and interact with apcs and doors within lavaland syndie outpost.

SO MANY CAMERAS
In the lavaland syndie outpost xenobio lab (with all the slimes) the cameras on the walls are dupicated each slime cell has two or more cameras on top of each other. they also have xray.

**Comment by CinderWC** [comment]
@Strazyplus Please make a new issue report regarding this one

**Comment by Commandersand** [comment]
@CinderWC up to date beta

**Comment by Commandersand** [comment]
@CinderWC up to date beta

**Comment by CinderWC** [comment]
@Commandersand 

First of all: You can get past the lava with an RCD, with an RCD that you can get from the autolathe if you hack it. But you shouldnt as you arent really supposed to leave the syndicate base

As for the console white screen issue: Downgrade your BYOND version to 512 (aka the stable branch). The server has downgraded to it as well due to performance issues and crashes because 513 (The beta branch) is incredibly goddamn unstable.

@Strazyplus I looked into your issues:

The Syndie xenobio cameras are xray, there are no duplicate cameras in there, i checked.

As for the AI being able to interact with the APCs and doors. It unfortunately is intended and is a common thing that pisses people off, i would genuinely enjoy for AIs to be z-level locked in the future

I will consider these issues fixed/intended unless there is anything else that is going on with this OR if any of the actual issues persist. You may reopen this ticket or create a new one
